serviceAccount:
  create: true
  name: karpenter
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::840489313276:role/eks-karpenter-demo-karpenter-controller

controller:
  env:
    - name: CLUSTER_NAME
      value: eks-karpenter-demo
    - name: CLUSTER_ENDPOINT
      value: https://15EF8B87C1A1AAEF460C177B948E5D89.gr7.us-east-1.eks.amazonaws.com

settings:
  aws:
    interruptionQueue: karpenter-eks-karpenter-demo

logLevel: info
